title: Machine Intelligence with COmbinatorial DATA
logo: "./mico-logo.png"
description: "A blog (for now)."
email: "cotta |at| purdue |dot| edu"
#twitter: "@cottascience"
theme: jekyll-theme-minimal
